// <auto-generated />
namespace ExamManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddMarkRounding : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMarkRounding));
        
        string IMigrationMetadata.Id
        {
            get { return "201808180016376_AddMarkRounding"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
